Untitled Pull Request
DaniilSukhanov/HW3_Reference pull request #1
Opened 2024-10-29 16:36 UTC by DaniilSukhanov

Homework

2024-10-30 17:01 UTC, SolarHaddock46 requested changes
почему залил в мейн до открытия пр? из-за этого из этого пр пропал файл GradientView. к коду в нем претензий особо нет, но заливать в мейн до завершения (и тем более до открытия) ревью - серьезное нарушение.
жду исправления комментов и добавления пропавших файлов в пр

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/AppFont.swift
> +    static let titleFont = UIFont.systemFont(ofSize: 24, weight: .bold)
этот шрифт используется только в вьюконтроллере, поэтому этот файл смысла не имеет и шрифт нужно перенести в вьюконтроллер как константу

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +    }()
эта анимация делается **намного** проще без таймера, просто с параметрами autoreverse и repeat

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +    private struct ConfigurationAnimationView {
1) если уж и делать такое, то это должно называться AnimationViewConfiguration
2) но так мы вообще не делаем, это просто еще две константы, назови их соответствующе и засунь к остальным.

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +    private var selectedAnimation: LottieAnimation?
не проще было реализовать выбор анимации так, как мы делали на лекции? тут даже еще проще, тк не надо хранить индекс и вычислять его по хитрым формулам при каждом переключении

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
>      private let gradientView = GradientView(colors: [AppColor.firstBackgroundColor, AppColor.secondBackgroundColor], duration: 3)
этого быть не должно

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +    private let speeds = [
поставить отступ и марк, чтобы разделить визуально объявления

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +        static let durationScaleAnimationButtonSubmit: TimeInterval = 1.5
ну хорошо же начал, и что опять стало с неймингом констант? названия в таком формате понять очень сложно, лучше писать, например, submitButtonWidth, чтобы сразу было понятно, чье это свойство и что это за свойство вообще
**все константы переименовать**

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +    }()
в этих стеквью не хватает спейсинга, заголовок если не вплотную стоит, то наезжает на селектор

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
>      }
убрать и реализовать анимацию без таймера

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
>      func setupGradualView() {
почему gradientView тут резко превратился в gradualView? переименуй

2024-10-30 17:01 UTC, SolarHaddock46 commented on .DS_Store
гитигнор составлен неверно, если этот файл есть

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +    }
эти две функции можно превратить в одну, потому что hideAnimationView вызывается только из showAnimationView буквально несколькими строками выше

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +            }
эту анимацию можно реализовать намного проще через CASpringAnimation

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +        }
вместо этой анимации можно было спокойно сделать алерт, но допустим
опыт с анимациями зато из этого получается хороший, для этой домашки это хорошо, но на реальных продуктах так не запариваются

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +        stack.addArrangedSubview(view)
от этих строк можно избавиться, сынициализировав стеквью здесь с аргументом arrangedSubviews

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +            animationView.centerYAnchor.constraint(equalTo: view.centerYAnchor),
лишнее, если и так на всю вьюху его растягиваешь

2024-10-30 17:01 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +        cell.textLabel?.text = "animation\(indexPath.row + 1)"
если бы анимации назывались не просто animation1, 2 и так далее, этот метод накрылся бы. переделай

2024-11-02 14:16 UTC, DaniilSukhanov commented on HW3_Reference/ViewController.swift
>      private let gradientView = GradientView(colors: [AppColor.firstBackgroundColor, AppColor.secondBackgroundColor], duration: 3)
Не очень понял. То есть не надо было отдельно создавать View, которая переливается?

2024-11-02 15:57 UTC, DaniilSukhanov commented on HW3_Reference/AppFont.swift
> +    static let titleFont = UIFont.systemFont(ofSize: 24, weight: .bold)
Вдруг какие-то еще шрифты понадобиться

2024-11-05 10:56 UTC, SolarHaddock46 approved these changes
в целом апрув, но некоторые изменения все же лучше внести

2024-11-05 10:56 UTC, SolarHaddock46 commented on HW3_Reference/AppFont.swift
> +    static let titleFont = UIFont.systemFont(ofSize: 24, weight: .bold)
это не наш случай, макет задания финальный, и шрифт там один, следовательно, такая конструкция для нашего случая - ненужный оверинжиниринг, удаляй

2024-11-05 10:56 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +        static let buttonSubmitCornerRadius: CGFloat = 10
submitButtonCornerRadius

2024-11-05 10:56 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +        Container(name: "Spider-man!", value: LottieAnimation.named("animation3"))
когда я говорил переработать систему отображения имен анимаций, я имел в виду сделать так, чтобы в таблице отображались имена самих файлов вне зависимости от того, есть ли в них индекс или нет
это _как бы_ подходит, но костыль, если я заменю файлы анимаций, это меню будет уже неактуальным

2024-11-05 10:56 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
>      private let gradientView = GradientView(colors: [AppColor.firstBackgroundColor, AppColor.secondBackgroundColor], duration: 3)
это можно было спокойно сделать без отдельного файла, но ладно, в данном случае прощаю, потому что кода там нормально так

2024-11-05 10:56 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
> +        Container(name: "Spider-man!", value: LottieAnimation.named("animation3"))
сам мув с массивом контейнеров хорош с точки зрения оптимизации кода в экстеншне хорош, просто сами имена стоит получать из файлов, а не из хардкода

2024-11-05 10:56 UTC, SolarHaddock46 commented on HW3_Reference/ViewController.swift
>                      }
такие конструкции лучше не плодить
а если и плодить - то писать в одну строку
например, `guard let self = self else { return }`

2024-11-23 13:52 UTC, merged